### ISSUE TITLE
[BUG] Clicking File From "Files Changed" View Doesnt Open File

### ISSUE THREAD

**Issue by jmrapp1** [krasimir/githorn#2]
**Problem**
If you don't have the "Files" tab opened (AKA you have the "Timeline" view open), when you click on a File from the "Files View" tree it won't open the file view. You have to open the "Files" tab for it to work

Tested on Google Chrome

**Comment by krasimir** [comment]
Good call. I already tried to fix that but it is a little bit tricky because the content of the "Files" page is not there if I just jump to it. The way of how the scrolling works is via an anchor link. In order to work I have to delay the URL update till the files are loaded and then change the page's address. Then the browser will scroll the page.

Definitely possible, I just want to find the cheapest way to do it. Will be there soon.

**Comment by jmrapp1** [comment]
I actually just fixed it locally! Very inexpensive, no additional dependencies, and no random delay while crossing your fingers it's long enough. Going to open a PR!

**Comment by krasimir** [comment]
Awesome! I would love to see the fix. I'll probably merge it tomorrow thought since it is a bit late here.

**Comment by jmrapp1** [comment]
Sure thing! Here's the PR: #4

**Comment by krasimir** [comment]
It's live. Released as `v.0.1.22`.
