### ISSUE TITLE
[SUGGESTION] Syntax Highlighting

### ISSUE THREAD

**Issue by jmrapp1** [krasimir/githorn#3]
Syntax highlighting on code files when viewing them in PRs would be very useful!

**Comment by krasimir** [comment]
That's also pretty challenging. That's because most of the syntax highlighters work on tokenization mechanism. Which means that they probably need the whole valid snippet in order to figure the colors. When we receive the git diff we don't actually have the full code. We have only portions of it. Will have to think about a smarter way to fix that.
